version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin.*"
          - "com.google.devtools.ksp"
          - "kotlin*"
          - "*kotlin*"
      spring:
        patterns:
          - "*spring*"
      micrometer:
        patterns:
          - "*micrometer*"

  - package-ecosystem: "npm"
    directory: "/moving-objects-gui"
    schedule:
      interval: "daily"
    groups:
      angular:
        patterns:
          - "@angular*"
          - "angular*"

  - package-ecosystem: "npm"
    directory: "/e2e"
    schedule:
      interval: "daily"
