version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/moving-objects-gui"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/e2e"
    schedule:
      interval: "daily"
