image: cimg/openjdk:18.0.1

pipelines:
  branches:
    master:
      - step:
          caches:
            - gradle
          script:
            - make buildw
  custom:
      renovate:
        - step:
            image: renovate/renovate
            caches:
              - maven
            script:
              - export RENOVATE_CONFIG=$(< renovate.json)
              - renovate
