image: jesperancinha/je-all-build-jdk-14:0.0.2

pipelines:
  default:
    - step:
        caches:
          - gradle
        script:
          - gradle clean build install test
  custom:
      renovate:
        - step:
            image: renovate/renovate
            caches:
              - maven
            script:
              - export RENOVATE_CONFIG=$(< renovate.json)
              - renovate
