version: "3.7"
services:
  moving-objects-oauth-service:
    ports:
      - "8081:8081"

  moving-objects-rest-service:
    ports:
      - "8082:8082"

  prometheus:
    ports:
      - "9090:9090"

  grafana:
    ports:
      - "3000:3000"

  influxdb:
    ports:
      - "8086:8086"

  nginx:
    ports:
      - "8080:80"

  mosdb:
    ports:
      - "5432:5432"
