services:
  moving-objects-jwt-service:
    env_file:
      - .env
    environment:
      - MOS_DB_IP=${MOS_DB_IP}
    hostname: moving-objects-jwt-service
    container_name: moving-objects-jwt-service
    build:
      context: moving-objects-jwt-service/.
    depends_on:
      mosdb:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 350M
        reservations:
          memory: 350M
    networks:
      - mos_net
    healthcheck:
      test: ["CMD", "curl", "--silent", "http://127.0.0.1:8081/objects/actuator"]
      interval: 5s
      timeout: 240s
      retries: 60

  moving-objects-rest-service:
    env_file:
      - .env
    environment:
      - ISSUER=$ISSUER
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDIRECT_URL=${REDIRECT_URL}
    hostname: moving-objects-rest-service
    container_name: moving-objects-rest-service
    build:
      context: moving-objects-rest-service/.
    depends_on:
      mosdb:
        condition: service_healthy
      moving-objects-jwt-service:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 350M
        reservations:
          memory: 350M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      - mos_net
    healthcheck:
      test: ["CMD", "curl", "--silent", "http:/127.0.0.1:8082/aggregator/actuator"]
      interval: 5s
      timeout: 240s
      retries: 60

  prometheus:
    hostname: prometheus
    container_name: prometheus
    build:
      context: docker-files/prometheus/.
    networks:
      - mos_net
    deploy:
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 50M

  grafana:
    hostname: grafana
    container_name: grafana
    build:
      context: docker-files/grafana/.
    networks:
      - mos_net
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 100M

  influxdb:
    hostname: influxdb
    container_name: influxdb
    build:
      context: docker-files/influxdb/.
    networks:
      - mos_net
    deploy:
      resources:
        limits:
          memory: 400M
        reservations:
          memory: 400M

  nginx:
    hostname: nginx
    container_name: nginx
    build:
      context: ./moving-objects-gui/.
    restart: on-failure
    networks:
      - mos_net
    depends_on:
      moving-objects-jwt-service:
        condition: service_healthy
      moving-objects-rest-service:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 100M

  mosdb:
    hostname: mosdb
    container_name: mosdb
    image: postgres:14.5
    command: -c 'max_connections=400' -c 'shared_buffers=100MB'
    volumes:
      - ./docker-files/docker-psql:/docker-entrypoint-initdb.d
      - ./docker-files/docker-psql/multiple:/docker-entrypoint-initdb.d/multiple
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_MULTIPLE_DATABASES: mos
    expose:
      - "5432"
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 100M
    networks:
      - mos_net
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 0s

networks:
  mos_net:
