version: "3.7"
services:
  moving-objects-oauth-service:
    env_file:
      - .env
    environment:
      - MOS_DB_IP=${MOS_DB_IP}
    hostname: moving-objects-oauth-service
    container_name: moving-objects-oauth-service
    build:
      context: moving-objects-oauth-service/.
    depends_on:
      - mosdb
    networks:
      mos_net:
        ipv4_address: ${MOS_AIRPORTS_OAUTH_IP}

  moving-objects-rest-service:
    env_file:
      - .env
    hostname: moving-objects-rest-service
    container_name: moving-objects-rest-service
    build:
      context: moving-objects-rest-service/.
    depends_on:
      - mosdb
    networks:
      mos_net:
        ipv4_address: ${MOS_AIRPORTS_IP}

  prometheus:
    hostname: prometheus
    container_name: ias-prometheus
    build:
      context: docker-files/prometheus/.
    networks:
      mos_net:
        ipv4_address: ${MOS_PROMETHEUS_IP}

  grafana:
    hostname: grafana
    container_name: ias-grafana
    build:
      context: docker-files/grafana/.
    networks:
      mos_net:
        ipv4_address: ${MOS_GRAFANA_IP}

  influxdb:
    hostname: influxdb
    container_name: ias-influxdb
    build:
      context: docker-files/influxdb/.
    networks:
      mos_net:
        ipv4_address: ${MOS_INFLUX_IP}

  nginx:
    hostname: nginx
    container_name: nginx
    build:
      context: ./moving-objects-gui/.
    ports:
      - "8080:80"
    restart: on-failure
    networks:
      mos_net:
        ipv4_address: ${MOS_NGINX_IP}

  mosdb:
    hostname: mosdb
    container_name: mosdb
    image: postgres:14.1
    volumes:
      - ./docker-files/docker-psql:/docker-entrypoint-initdb.d
      - ./docker-files/docker-psql/multiple:/docker-entrypoint-initdb.d/multiple
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_MULTIPLE_DATABASES: mos
    expose:
      - "5432"
    networks:
      mos_net:
        ipv4_address: ${MOS_DB_IP}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 0s

  gui-builder:
    container_name: moving-objects-gui-build
    build:
      context: .
    volumes:
      - ./moving-objects-gui:/opt/moving-objects-gui
      - ./e2e:/opt/e2e
      - ./moving-objects-gui/node_modules:/opt/moving-objects-gui/node_modules
      - ./e2e/node_modules:/opt/e2e/node_modules
    user: "1000:1000"
    entrypoint: ["cd", "/opt/moving-objects-gui", "&&", "yarn", "&&", "npm", "run", "build-docker", "&&", "cd", "../e2e", "&&", "yarn"]
    networks:
      - mos_net

networks:
  mos_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}

