version: "3.7"
services:
  airports:
    ports:
     - "8081:8081"
     - "8082:8082"
      - "4000:4000"
      - "8080:80"

  prometheus:
    ports:
      - "9090:9090"

  grafana:
    ports:
      - "3000:3000"

  influxdb:
    ports:
      - "8086:8086"

  nginx:
    ports:
      - "8080:80"
