version: "3.7"
services:
  gui-builder:
    container_name: moving-objects-gui-build
    build:
      context: .
    volumes:
      - ./moving-objects-gui:/opt/moving-objects-gui
      - ./e2e:/opt/e2e
      - ./moving-objects-gui/node_modules:/opt/moving-objects-gui/node_modules
      - ./e2e/node_modules:/opt/e2e/node_modules
    user: "1000:1000"
    networks:
      - mos_net