version: "3.7"
services:
  gui-builder:
    container_name: moving-objects-gui-build
    build:
      context: ./docker-files/build-node/.
    volumes:
      - ./moving-objects-gui:/opt/moving-objects-gui
      - ./e2e:/opt/e2e
    user: "1000:1000"
    networks:
      - mos_net

  cypress-builder:
    container_name: news-cast-cypress-build
    build:
      context: ./docker-files/build-cypress/.
    volumes:
      - ./e2e:/opt/e2e
    user: "1000:1000"
    networks:
      - mos_net
