{
 "title": "Node JS",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Status",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Active Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nodejs_active_requests" }
   ]
  },
  {
   "title": "Used Heap",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nodejs_heap_size_used_bytes" }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 12, "w": 7, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nodejs_eventloop_lag_seconds" }
   ]
  },
  {
   "title": "External Memory",
   "type": "graph",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nodejs_external_memory_bytes" }
   ]
  }
 ]
}