 # Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build-gradle:
    docker:
      - image: cimg/openjdk:17.0.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: make buildw && gradle -i

  build-yarn:
    docker:
      - image: cimg/node:17.3.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run:
          command: yarn install --force
          working_directory: international-airports-gui

      - run:
          command: yarn
          working_directory: international-airports-gui

  report-all:
    docker:
      - image: cimg/openjdk:17.0.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: sudo apt update
      - run: sudo apt install npm
      - run: npm i -g yarn
      - run: cd international-airports-gui && yarn && npm run coverage
      - run: make buildw && gradle -i

workflows:
  version: 2
  build_all:
    jobs:
      - report-all
      - build-gradle
      - build-yarn
