version: 2
jobs:
  build-gradle:
    docker:
      - image: cimg/openjdk:17.0.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: make buildw && gradle -i

  build-yarn:
    docker:
      - image: cimg/node:17.3.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run:
          command: yarn install --force
          working_directory: international-airports-gui

      - run:
          command: yarn
          working_directory: international-airports-gui

  report-all:
    docker:
      - image: cimg/openjdk:17.0.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: sudo apt update
      - run: sudo apt install npm
      - run: sudo npm i -g yarn
      - run: sudo npm install -g n
      - run: sudo n stable
      - run: cd international-airports-gui && yarn && yarn add jest && npm run coverage
      - run: make buildw && gradle -i

workflows:
  version: 2
  build_all:
    jobs:
      - build-gradle
      - build-yarn
      - report-all
