{
 "title": "Java Virtual Machines",
 "tags": [ "prometheus" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Scrape Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5, max(scrape_duration_seconds) by (job))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Profile",
   "type": "graph",
   "gridPos": { "h": 12, "w": 9, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "jvm_memory_used_bytes" }
   ]
  },
  {
   "title": "Number of requests  (last minute)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "Status",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Total Logback Events",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "logback_events_total",
     "legendFormat": "{{level}} - {{instance}} - {{job}} "
    }
   ]
  },
  {
   "title": "Head Block GC Activity",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_gc_live_data_size_bytes" }
   ]
  },
  {
   "title": "Process Open Files",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 7, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_files_open_files" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "system_cpu_usage" }
   ]
  }
 ]
}