version: '3.7'
services:
  e2e-electron:
    build:
      context: .
    working_dir: /e2e
    entrypoint: ["npx","cypress", "run", "--browser", "electron", "--env", "host=nginx"]
    volumes:
      - ../e2e:/e2e

  e2e-chrome:
    build:
      context: .
    working_dir: /e2e
    command: "npx cypress run --browser chrome --env host=nginx"
    volumes:
      - ../e2e:/e2e

  e2e-firefox:
    build:
      context: .
    working_dir: /e2e
    command: "npx cypress run --browser firefox --env host=nginx"
    volumes:
      - ../e2e:/e2e

  e2e-edge:
    build:
      context: .
    working_dir: /e2e
    command: "npx cypress run --browser edge --env host=nginx"
    volumes:
      - ../e2e:/e2e
