version: '3.7'
services:
  e2e-electron:
    image: "cypress/included:10.3.1"
    working_dir: /e2e
    command: "--browser electron --env host=192.168.0.15,port=80"
    deploy:
      resources:
        limits:
          memory: 800M
        reservations:
          memory: 800M
    volumes:
      - ./e2e:/e2e
    networks:
      - mos_net

  e2e-chrome:
    image: "cypress/included:10.3.1"
    working_dir: /e2e
    command: "--browser chrome --env host=192.168.0.15,port=80"
    deploy:
      resources:
        limits:
          memory: 800M
        reservations:
          memory: 800M
    volumes:
      - ./e2e:/e2e
    networks:
      - mos_net

  e2e-firefox:
    image: "cypress/included:10.3.1"
    working_dir: /e2e
    command: "--browser firefox --env host=192.168.0.15,port=80"
    deploy:
      resources:
        limits:
          memory: 800M
        reservations:
          memory: 800M
    volumes:
      - ./e2e:/e2e
    networks:
      - mos_net

  e2e-edge:
    image: "cypress/included:10.3.1"
    working_dir: /e2e
    command: "--browser edge --env host=192.168.0.15,port=80"
    deploy:
      resources:
        limits:
          memory: 800M
        reservations:
          memory: 800M
    volumes:
      - ./e2e:/e2e
    networks:
      - mos_net
