version: '3.7'
services:
  e2e-electron:
    image: "cypress/included:13.12.0"
    working_dir: /e2e
    command: "--browser electron --env host=nginx,port=8080 --config defaultCommandTimeout=15000,requestTimeout=15000"
    volumes:
      - ./e2e:/e2e
      - .env:/.env
      - ./docker-files/telegraf:/docker-files/telegraf
    networks:
      - mos_net

  e2e-chrome:
    image: "cypress/included:13.12.0"
    working_dir: /e2e
    command: "--browser chrome --env host=nginx,port=8080 --config defaultCommandTimeout=15000,requestTimeout=15000"
    volumes:
      - ./e2e:/e2e
      - .env:/.env
      - ./docker-files/telegraf:/docker-files/telegraf
    networks:
      - mos_net

  e2e-firefox:
    image: "cypress/included:13.12.0"
    working_dir: /e2e
    command: "--browser firefox --env host=nginx,port=8080 --config defaultCommandTimeout=15000,requestTimeout=15000"
    volumes:
      - ./e2e:/e2e
      - .env:/.env
      - ./docker-files/telegraf:/docker-files/telegraf
    networks:
      - mos_net

  e2e-firefox-full:
    image: "cypress/included:13.12.0"
    working_dir: /e2e
    command: "--config-file full.cypress.config.ts --browser firefox --env host=nginx,port=8080 --config defaultCommandTimeout=15000,requestTimeout=15000"
    volumes:
      - ./e2e:/e2e
      - .env:/.env
      - ./docker-files/telegraf:/docker-files/telegraf
    networks:
      - mos_net

  e2e-edge:
    image: "cypress/included:13.12.0"
    working_dir: /e2e
    command: "--browser edge --env host=nginx,port=8080 --config defaultCommandTimeout=15000,requestTimeout=15000"
    volumes:
      - ./e2e:/e2e
      - .env:/.env
      - ./docker-files/telegraf:/docker-files/telegraf
    networks:
      - mos_net
