export const oktaConfig = {
    CLIENT_ID: "${CLIENT_ID}",
    CLIENT_SECRET: "",
    ISSUER: "${ISSUER}",
    REDIRECT_LOGOUT: "${REDIRECT_LOGOUT}",
    REDIRECT_SERVICE_URL: "${REDIRECT_SERVICE_URL}",
    REDIRECT_URL: "${REDIRECT_URL}",
};
