name: mos-app

on:
  push:
    branches: [ main ]
  pull_request_target:
    types:
      - closed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
      with:
        gradle-version: 8.10.1

    - name: Generate credentials
      run:  make generate-credentials

    - name: Build Gradle
      run:  make build-gradle

    - name: Test Gradle
      run:  make test-gradle

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Build Node JS and Test
      run: make build-test-npm

    - name: Coverage Reports
      run: make report-coverage
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      continue-on-error: true
